export const FETCH_HISTORY_START = 'FETCH_HISTORY_START';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_FAIL = 'FETCH_HISTORY_FAIL';
export const FETCH_PAYLOAD_START = "FETCH_PAYLOAD_START";
export const FETCH_PAYLOAD_SUCCESS = 'FETCH_PAYLOAD_SUCCESS';
export const FETCH_PAYLOAD_FAIL = 'FETCH_PAYLOAD_FAIL';